### PR TITLE
Move sync factory to parameter packs.

### PR DESCRIPTION
**Pull request by vysotskiyserhiy**

### CODE REVIEW

**Comment by patron-ghigley** [comment]
@vysotskiyserhiy Thanks for this! I'll check it out this evening after work. (I'm on the east coast of the US.)

**Comment by vysotskiyserhiy** [comment]
Sure2 окт. 2023 г., в 18:17, Gregory Higley ***@***.***> написал(а):﻿
@vysotskiyserhiy Thanks for this! I'll check it out this evening after work. (I'm on the east coast of the US.)

**Comment by vysotskiyserhiy** [comment]
Sure

**Comment by vysotskiyserhiy** [comment]
@patron-ghigley @Revolucent any comments on this ?

**Pull request closed without merging**
